openapi: 3.0.0
info:
  title: Educational Content API for NVIDIA Isaac Module
  description: API for retrieving educational content about NVIDIA Isaac technologies
  version: 1.0.0
  contact:
    name: AI-Robot Brain Module Team
    email: education@nvidia-isaac-ai-robot.example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /educational-content/isaac-sim:
    get:
      summary: Get Isaac Sim educational content
      description: Retrieve educational content covering NVIDIA Isaac Sim and its role in AI-robot systems
      operationId: getIsaacSimContent
      tags:
        - educational-content
      parameters:
        - name: format
          in: query
          description: Response format preference
          required: false
          schema:
            type: string
            enum: [full, summary, assessment]
            default: full
      responses:
        '200':
          description: Isaac Sim educational content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsaacSimContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /educational-content/isaac-ros:
    get:
      summary: Get Isaac ROS educational content
      description: Retrieve educational content covering Isaac ROS and accelerated perception
      operationId: getIsaacROSContent
      tags:
        - educational-content
      parameters:
        - name: format
          in: query
          description: Response format preference
          required: false
          schema:
            type: string
            enum: [full, summary, assessment]
            default: full
      responses:
        '200':
          description: Isaac ROS educational content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsaacROSContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /educational-content/nav2-humanoid:
    get:
      summary: Get Nav2 Humanoid Navigation educational content
      description: Retrieve educational content covering Nav2 navigation for humanoid robots
      operationId: getNav2HumanoidContent
      tags:
        - educational-content
      parameters:
        - name: format
          in: query
          description: Response format preference
          required: false
          schema:
            type: string
            enum: [full, summary, assessment]
            default: full
      responses:
        '200':
          description: Nav2 Humanoid Navigation educational content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nav2HumanoidContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /educational-content/search:
    post:
      summary: Search educational content
      description: Search across all educational content for specific topics
      operationId: searchEducationalContent
      tags:
        - educational-content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results containing relevant educational content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    IsaacSimContent:
      type: object
      required:
        - id
        - title
        - content
        - learning_objectives
        - assessment_questions
      properties:
        id:
          type: string
          description: Unique identifier for the Isaac Sim content
          example: "isaac-sim-overview-001"
        title:
          type: string
          description: Title of the Isaac Sim content
          example: "NVIDIA Isaac Sim Overview"
        content:
          type: object
          properties:
            overview:
              type: string
              description: Introduction to Isaac Sim and its role in AI-robot systems
            photorealistic_simulation:
              type: string
              description: Explanation of photorealistic simulation concepts
            synthetic_data_generation:
              type: string
              description: Coverage of synthetic data generation methods and benefits
            training_vs_testing:
              type: string
              description: Differentiation between training and testing environments
            best_practices:
              type: string
              description: Recommended practices for using Isaac Sim
            examples:
              type: array
              items:
                type: string
              description: Practical examples and use cases
        learning_objectives:
          type: array
          items:
            type: string
          description: Specific learning objectives for this chapter
          example:
            - "Explain the role of photorealistic simulation in robotics development"
            - "Describe how synthetic data generation accelerates AI development"
        assessment_questions:
          type: array
          items:
            $ref: '#/components/schemas/AssessmentQuestion'
        prerequisites:
          type: array
          items:
            type: string
          description: Knowledge required before this chapter
        cross_references:
          type: array
          items:
            type: string
          description: Links to related content in other chapters

    IsaacROSContent:
      type: object
      required:
        - id
        - title
        - content
        - learning_objectives
        - assessment_questions
      properties:
        id:
          type: string
          description: Unique identifier for the Isaac ROS content
          example: "isaac-ros-perception-001"
        title:
          type: string
          description: Title of the Isaac ROS content
          example: "Isaac ROS & Accelerated Perception"
        content:
          type: object
          properties:
            overview:
              type: string
              description: Introduction to Isaac ROS and its role in perception
            hardware_accelerated_vslam:
              type: string
              description: Explanation of hardware-accelerated VSLAM concepts
            sensor_pipelines:
              type: string
              description: Description of sensor pipeline architectures
            perception_stacks:
              type: string
              description: Coverage of perception stack components
            ros2_integration:
              type: string
              description: Explanation of Isaac ROS integration with ROS 2
            best_practices:
              type: string
              description: Recommended practices for accelerated perception
            examples:
              type: array
              items:
                type: string
              description: Practical examples and use cases
        learning_objectives:
          type: array
          items:
            type: string
          description: Specific learning objectives for this chapter
        assessment_questions:
          type: array
          items:
            $ref: '#/components/schemas/AssessmentQuestion'
        prerequisites:
          type: array
          items:
            type: string
          description: Knowledge required before this chapter
        cross_references:
          type: array
          items:
            type: string
          description: Links to related content in other chapters

    Nav2HumanoidContent:
      type: object
      required:
        - id
        - title
        - content
        - learning_objectives
        - assessment_questions
      properties:
        id:
          type: string
          description: Unique identifier for the Nav2 Humanoid content
          example: "nav2-humanoid-navigation-001"
        title:
          type: string
          description: Title of the Nav2 Humanoid content
          example: "Navigation with Nav2 for Humanoid Robots"
        content:
          type: object
          properties:
            overview:
              type: string
              description: Introduction to Nav2 and navigation for humanoid robots
            path_planning_fundamentals:
              type: string
              description: Explanation of path planning concepts for humanoid robots
            humanoid_movement_considerations:
              type: string
              description: Coverage of humanoid-specific navigation challenges
            navigation_pipelines:
              type: string
              description: Description of navigation pipeline architectures
            bipedal_navigation:
              type: string
              description: Specifics of navigation for bipedal robots
            best_practices:
              type: string
              description: Recommended practices for humanoid navigation
            examples:
              type: array
              items:
                type: string
              description: Practical examples and use cases
        learning_objectives:
          type: array
          items:
            type: string
          description: Specific learning objectives for this chapter
        assessment_questions:
          type: array
          items:
            $ref: '#/components/schemas/AssessmentQuestion'
        prerequisites:
          type: array
          items:
            type: string
          description: Knowledge required before this chapter
        cross_references:
          type: array
          items:
            type: string
          description: Links to related content in other chapters

    AssessmentQuestion:
      type: object
      required:
        - id
        - question
        - options
        - correct_answer
        - explanation
      properties:
        id:
          type: string
          description: Unique identifier for the question
        question:
          type: string
          description: The question text
        options:
          type: array
          items:
            type: string
          description: Multiple choice options
        correct_answer:
          type: string
          description: The correct option
        explanation:
          type: string
          description: Explanation of the correct answer

    SearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Search query text
          example: "VSLAM"
        filters:
          type: object
          properties:
            content_type:
              type: string
              enum: [isaac-sim, isaac-ros, nav2-humanoid]
              description: Filter by content type
            difficulty:
              type: string
              enum: [beginner, intermediate, advanced]
              description: Filter by difficulty level
        limit:
          type: integer
          description: Maximum number of results to return
          default: 10
          maximum: 100

    SearchResponse:
      type: object
      required:
        - results
        - total_count
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
        total_count:
          type: integer
          description: Total number of matching results
        query_time_ms:
          type: integer
          description: Time taken to execute the search in milliseconds

    SearchResult:
      type: object
      required:
        - id
        - title
        - content_type
        - relevance_score
        - snippet
      properties:
        id:
          type: string
          description: Unique identifier for the content
        title:
          type: string
          description: Title of the content
        content_type:
          type: string
          enum: [isaac-sim, isaac-ros, nav2-humanoid]
          description: Type of content
        relevance_score:
          type: number
          description: Relevance score for the search result
          minimum: 0
          maximum: 1
        snippet:
          type: string
          description: Snippet of content that matches the search

    BadRequest:
      type: object
      properties:
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Invalid request parameters"
        code:
          type: integer
          example: 400

    NotFound:
      type: object
      properties:
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "The requested resource was not found"
        code:
          type: integer
          example: 404

    InternalServerError:
      type: object
      properties:
        error:
          type: string
          example: "Internal Server Error"
        message:
          type: string
          example: "An unexpected error occurred"
        code:
          type: integer
          example: 500

  responses:
    BadRequest:
      description: Bad request - invalid parameters or payload
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'

tags:
  - name: educational-content
    description: Endpoints for retrieving educational content about NVIDIA Isaac technologies